name: nyx_user_addresses
description: Prueba técnica - Flutter (usuarios y direcciones)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  mocktail: ^1.0.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/locations_co.json
